# Generated by Django 4.1.1 on 2022-09-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=150)),
                ('author_name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
